### ISSUE TITLE
Incomplete support for filename characters on non-unicode servers

### ISSUE THREAD

**Issue by GarThor** [microsoft/p4vfs#15]
Experienced an error syncing today on a file with an accent character [specifically é] in its name.  Virtual syncs result in a file with a � character in its place.  Opening the file results in errors (probably because p4vfs has trouble figuring out the actual file name to force sync).

As a workaround force syncing using the normal p4 method worked fine.

**Comment by GarThor** [comment]
Looking through my depot, I found a few other files with this same issue, though with various other characters... Áόϋ... etc...

Looks like this might be because you are using string(char) instead of wstring(wchar) for your depot path names?

**Comment by jessk-msft** [comment]
Hi GarThor,

You are certainly correct about P4VFS missing proper support unicode characters in perforce depot paths, and essentially unicode mode perforce servers. While all of the P4VFS core service, driver, and command line tool is entirely 16bit wide character strings, the P4API related code (ie. DepotString) is multibyte char string and generally assumes UTF-8. I suspect there are bugs in the DepotString usage where it's assuming a Windows-1252 encoding instead of UTF-8.

There was some recent work in on the test `UnitTestServer.CreateDuplicatePerforceServer` with the goal to also run a suite of tests on a Unicode enabled server. I think that would be the next step for flushing out issues to provide proper unicode mode server support. 

Regards
jessk-msft

**Comment by GarThor** [comment]
Does this mean the error exists in the p4 C# API and not in the ms-p4vfs tool?  I haven't used the p4 C# API before, so I'm not familiar where the documentation is for that, or how it's used.

**Comment by GarThor** [comment]
Is there a timeline for fixing this issue?  It's been a while since the issue was originally posted...

**Comment by jessk-msft** [comment]
Hi GarThor,
Can you confirm if your Perforce server is running in Unicode mode?
> To check if a Perforce server is running in Unicode mode, you can use the p4 info command. [If the server is running in Unicode mode, the output of this command will include the following line: Server charset: utf8 ](https://www.perforce.com/manuals/p4sag/Content/P4SAG/superuser.unicode.setup.html)[1](https://www.perforce.com/manuals/p4sag/Content/P4SAG/superuser.unicode.setup.html).

**Comment by jessk-msft** [comment]
I've reproduced this problem on a non-unicode server as well. 
For example, added file:
`//depot/Misc/fooé.txt`

Then sync with p4vfs results in incorrect character translation:
```c:\P4DemoWorkspaces\bruno_ws\Misc>p4vfs sync //depot/Misc/...
P4VFS version 1.25.1.0
Virtual Sync: ["//depot/Misc/..."] Normal Atomic @12106
Started at [07/06/2023-12:05:14] version [1.25.1.0]
8 Modification messages to act on.
//depot/Misc/foo∩┐╜.txt#1 - installed as C:\P4DemoWorkspaces\bruno_ws\Misc\foo∩┐╜.txt```

I agree that P4VFS should made to support this, and properly support UTF8 throughout the codebase.
I can't give an exact ETA on when it'll be fixed, but I'll try to make time soon.

**Comment by GarThor** [comment]
> I've reproduced this problem on a non-unicode server as well. For example, added file: `//depot/Misc/fooé.txt`
> 
> Then sync with p4vfs results in incorrect character translation:
> 
> ```
> c:\P4DemoWorkspaces\bruno_ws\Misc>p4vfs sync //depot/Misc/...
> P4VFS version 1.25.1.0
> Virtual Sync: ["//depot/Misc/..."] Normal Atomic @12106
> Started at [07/06/2023-12:05:14] version [1.25.1.0]
> 8 Modification messages to act on.
> //depot/Misc/foo∩┐╜.txt#1 - installed as C:\P4DemoWorkspaces\bruno_ws\Misc\foo∩┐╜.txt
> ```
> 
> I agree that P4VFS should made to support this, and properly support UTF8 throughout the codebase. I can't give an exact ETA on when it'll be fixed, but I'll try to make time soon.

Thanks Jessk, I appreciate it... :D

**Comment by jessk-msft** [comment]
Fixed in release 1.26.1.0

**Comment by GarThor** [comment]
> Fixed in release 1.26.1.0

Thanks so much Jessk-msft!
I will go ahead and update asap! :D

**Comment by GarThor** [comment]
Hey @jessk-msft ,

I gave the latest version a try, however I still see weird output, which is prompting a little confusion.  I thought it wasn't working at first, but when I look in the directory the file exists with the right characters...

<img width="268" alt="image" src="https://github.com/microsoft/p4vfs/assets/43391503/b5d00d6e-1dac-47ac-842f-931d6914ab2c">

File names after this message also include the ≤ character instead of the ó character, and then it gives a summary that looks accurate.

**Comment by jessk-msft** [comment]
I see the same behavior with p4.exe
My terminal encoding doesn't seem to translate the characters properly.


From

**Comment by GarThor** [comment]
> I see the same behavior with p4.exe My terminal encoding doesn't seem to translate the characters properly.

I was wondering about that, but pasted characters seem to work fine in my terminal, which seems to indicate the problem isn't with the terminal (powershell/ms terminal) itself, but rather something weird going on with the application...

I hadn't tried the regular p4 service, but I get similar results to your screenshots for p4vfs.

**Comment by jessk-msft** [comment]
I'm seeing the same behavior in a powershell prompt, side-by-side with p4.exe
![image](https://github.com/microsoft/p4vfs/assets/44536565/310090e8-fa51-4529-822c-7f813cbea084)

Seeing as the `dir` command is properly displaying the filenames, we should be able to fix P4VFS to display them correctly as well. Sounds like a separate issue though.

**Comment by GarThor** [comment]
> I'm seeing the same behavior in a powershell prompt, side-by-side with p4.exe ![image](https://user-images.githubusercontent.com/44536565/254047661-310090e8-fa51-4529-822c-7f813cbea084.png)
> 
> Seeing as the `dir` command is properly displaying the filenames, we should be able to fix P4VFS to display them correctly as well. Sounds like a separate issue though.

Sounds good, lmk if you want me to create a separate issue for it.

**Comment by jessk-msft** [comment]
Sure I think that this console output is worth fixing. If p4vfs.exe is running with a console attached, then it *should* be required to display output using the console's codepage. 

Here's another example showing how my default ANSI codepage for cmd.exe is [CP-437](https://en.wikipedia.org/wiki/Code_page_437).
Both `p4.exe` and `p4vfs.exe` expect Windows-1252 [CP-1252](https://en.wikipedia.org/wiki/Code_page_1252)

We can use `chcp.com` to get/set the current console codepage:

![image](https://github.com/microsoft/p4vfs/assets/44536565/8c351395-3e27-473d-b60e-9d1cb7f6394c)

**Comment by GarThor** [comment]
> Sure I think that this console output is worth fixing. If p4vfs.exe is running with a console attached, then it _should_ be required to display output using the console's codepage. @GarThor, go ahead and create a P4VFS issue for it :)
> 
> Here's another example showing how my default ANSI codepage for cmd.exe is [CP-437](https://en.wikipedia.org/wiki/Code_page_437). Both `p4.exe` and `p4vfs.exe` expect Windows-1252 [CP-1252](https://en.wikipedia.org/wiki/Code_page_1252)
> 
> We can use `chcp.com` to get/set the current console codepage:
> 
> ![image](https://user-images.githubusercontent.com/44536565/254101644-8c351395-3e27-473d-b60e-9d1cb7f6394c.png)

Ok, posted new thread: https://github.com/microsoft/p4vfs/issues/27

**Comment by jessk-msft** [comment]
Closed. Follow up with #27
